# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attack_tracking_SendRoutingInfoForGPRS.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 633)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.netindicator = QtWidgets.QLineEdit(self.centralwidget)
        self.netindicator.setGeometry(QtCore.QRect(200, 180, 311, 31))
        self.netindicator.setObjectName("netindicator")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 170, 201, 31))
        self.label_5.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_5.setObjectName("label_5")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(480, 430, 181, 31))
        self.label_13.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_13.setObjectName("label_13")
        self.run = QtWidgets.QPushButton(self.centralwidget)
        self.run.setGeometry(QtCore.QRect(429, 380, 191, 41))
        self.run.setObjectName("run")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 90, 131, 21))
        self.label_3.setStyleSheet("font: 16pt \"Noto Sans\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 131, 21))
        self.label_2.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_2.setObjectName("label_2")
        self.sport = QtWidgets.QLineEdit(self.centralwidget)
        self.sport.setGeometry(QtCore.QRect(200, 140, 311, 31))
        self.sport.setObjectName("sport")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 151, 21))
        self.label.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label.setObjectName("label")
        self.cip = QtWidgets.QLineEdit(self.centralwidget)
        self.cip.setGeometry(QtCore.QRect(200, 10, 301, 31))
        self.cip.setObjectName("cip")
        self.sip = QtWidgets.QLineEdit(self.centralwidget)
        self.sip.setGeometry(QtCore.QRect(200, 100, 311, 31))
        self.sip.setObjectName("sip")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 130, 131, 21))
        self.label_4.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 230, 201, 31))
        self.label_6.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_6.setObjectName("label_6")
        self.hlr = QtWidgets.QLineEdit(self.centralwidget)
        self.hlr.setGeometry(QtCore.QRect(190, 230, 311, 31))
        self.hlr.setObjectName("hlr")
        self.cport = QtWidgets.QLineEdit(self.centralwidget)
        self.cport.setGeometry(QtCore.QRect(200, 50, 311, 41))
        self.cport.setObjectName("cport")
        self.output = QtWidgets.QTextEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(-10, 460, 1561, 191))
        self.output.setObjectName("output")
        self.imsi = QtWidgets.QLineEdit(self.centralwidget)
        self.imsi.setGeometry(QtCore.QRect(190, 280, 311, 31))
        self.imsi.setObjectName("imsi")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 280, 201, 31))
        self.label_10.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_10.setObjectName("label_10")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(0, 340, 201, 31))
        self.label_25.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_25.setObjectName("label_25")
        self.ggsn = QtWidgets.QLineEdit(self.centralwidget)
        self.ggsn.setGeometry(QtCore.QRect(210, 340, 311, 31))
        self.ggsn.setObjectName("ggsn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Attacker_tracking_SendRoutingInfoForGPRS"))
        self.netindicator.setText(_translate("MainWindow", "(i.e 0)"))
        self.label_5.setText(_translate("MainWindow", "Network_Indicator"))
        self.label_13.setText(_translate("MainWindow", "Output"))
        self.run.setText(_translate("MainWindow", "run"))
        self.label_3.setText(_translate("MainWindow", "server_ip"))
        self.label_2.setText(_translate("MainWindow", "client_port"))
        self.sport.setText(_translate("MainWindow", "(i.e 2906)"))
        self.label.setText(_translate("MainWindow", "client_ip"))
        self.cip.setText(_translate("MainWindow", "(i.e 192.168.56.101)"))
        self.sip.setText(_translate("MainWindow", "(i.e 192.168.56.102)"))
        self.label_4.setText(_translate("MainWindow", "server_port"))
        self.label_6.setText(_translate("MainWindow", "Targer_HLR"))
        self.hlr.setText(_translate("MainWindow", "(i.e 201179008255)"))
        self.cport.setText(_translate("MainWindow", "(i.e 2905)"))
        self.imsi.setText(_translate("MainWindow", "(i.e 602027891234567)"))
        self.label_10.setText(_translate("MainWindow", "Targer_IMSI"))
        self.label_25.setText(_translate("MainWindow", "Targer_GGSN"))
        self.ggsn.setText(_translate("MainWindow", "(i.e 201059996612)"))

        self.run.clicked.connect(self.runing)

    def runing(self):
        import attack_gui_web as atck_gui
        import os
        import subprocess as sp

        client_ip = str(self.cip.text()).replace(")","").replace("(","")
        client_port = str(self.cport.text()).replace(")","").replace("(","")
        server_ip = str(self.sip.text()).replace(")","").replace("(","")
        server_port = str(self.sport.text()).replace(")","").replace("(","")
        Network_Indicator = str(self.netindicator.text()).replace(")","").replace("(","")


        Targer_GGSN = str(self.ggsn.text()).replace(")","").replace("(","")

        Targer_HLR = str(self.hlr.text()).replace(")","").replace("(","")

        Targer_IMSI = str(self.imsi.text()).replace(")","").replace("(","")
        if(len(Targer_IMSI) < 15 or len(Targer_IMSI) > 16):
            from PyQt5.QtWidgets import  QPushButton, QMessageBox
            msgBox = QMessageBox()
            msgBox.setIcon(QMessageBox.Information)
            msgBox.setText("IMSI len should be 15 or 16")
            msgBox.setWindowTitle("IMSI Error")
            msgBox.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            returnValue = msgBox.exec()
            exit(0)

         

        atck_gui.attack_tracking_SendRoutingInfoForGPRS(client_ip,client_port,server_ip,server_port,Network_Indicator,Targer_IMSI,Targer_HLR,Targer_GGSN)
        data = open('outingss7.txt','r').read().replace('[0m',' \n ').replace('\x1b[31m',' \n ').replace('\x1b[32m',' \n ').replace('\x1b',' \n ').replace('[34m',' ')
        self.output.append(str(data))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
