# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attack_tracking_AnyTimeInterrogation.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(889, 630)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cip = QtWidgets.QLineEdit(self.centralwidget)
        self.cip.setGeometry(QtCore.QRect(200, 0, 301, 31))
        self.cip.setObjectName("cip")
        self.output = QtWidgets.QTextEdit(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(-49, 390, 1561, 191))
        self.output.setObjectName("output")
        self.cport = QtWidgets.QLineEdit(self.centralwidget)
        self.cport.setGeometry(QtCore.QRect(200, 40, 311, 41))
        self.cport.setObjectName("cport")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(441, 360, 181, 31))
        self.label_13.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_13.setObjectName("label_13")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 120, 131, 21))
        self.label_4.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_4.setObjectName("label_4")
        self.sport = QtWidgets.QLineEdit(self.centralwidget)
        self.sport.setGeometry(QtCore.QRect(200, 130, 311, 31))
        self.sport.setObjectName("sport")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 80, 131, 21))
        self.label_3.setStyleSheet("font: 16pt \"Noto Sans\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.msisdn = QtWidgets.QLineEdit(self.centralwidget)
        self.msisdn.setGeometry(QtCore.QRect(190, 220, 311, 31))
        self.msisdn.setObjectName("msisdn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 220, 201, 31))
        self.label_6.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 131, 21))
        self.label_2.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 151, 21))
        self.label.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 160, 201, 31))
        self.label_5.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_5.setObjectName("label_5")
        self.netindicator = QtWidgets.QLineEdit(self.centralwidget)
        self.netindicator.setGeometry(QtCore.QRect(200, 170, 311, 31))
        self.netindicator.setObjectName("netindicator")
        self.run = QtWidgets.QPushButton(self.centralwidget)
        self.run.setGeometry(QtCore.QRect(390, 310, 191, 41))
        self.run.setObjectName("run")
        self.sip = QtWidgets.QLineEdit(self.centralwidget)
        self.sip.setGeometry(QtCore.QRect(200, 90, 311, 31))
        self.sip.setObjectName("sip")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 270, 201, 31))
        self.label_10.setStyleSheet("font: 16pt \"Noto Sans\";")
        self.label_10.setObjectName("label_10")
        self.locael_gt = QtWidgets.QLineEdit(self.centralwidget)
        self.locael_gt.setGeometry(QtCore.QRect(190, 270, 311, 31))
        self.locael_gt.setObjectName("locael_gt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 889, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Attacker_tracking_AnyTimeInterrogation"))
        self.cip.setText(_translate("MainWindow", "(i.e 192.168.56.101)"))
        self.cport.setText(_translate("MainWindow", "(i.e 2905)"))
        self.label_13.setText(_translate("MainWindow", "Output"))
        self.label_4.setText(_translate("MainWindow", "server_port"))
        self.sport.setText(_translate("MainWindow", "(i.e 2906)"))
        self.label_3.setText(_translate("MainWindow", "server_ip"))
        self.msisdn.setText(_translate("MainWindow", "i.e 201522222222)"))
        self.label_6.setText(_translate("MainWindow", "Targer_MSISDN"))
        self.label_2.setText(_translate("MainWindow", "client_port"))
        self.label.setText(_translate("MainWindow", "client_ip"))
        self.label_5.setText(_translate("MainWindow", "Network_Indicator"))
        self.netindicator.setText(_translate("MainWindow", "(i.e 0)"))
        self.run.setText(_translate("MainWindow", "run"))
        self.sip.setText(_translate("MainWindow", "(i.e 192.168.56.102)"))
        self.label_10.setText(_translate("MainWindow", "locael_GT"))
        self.locael_gt.setText(_translate("MainWindow", "(i.e 96512345678)"))

        self.run.clicked.connect(self.runing)

    def runing(self):
        import attack_gui_web as atck_gui
        import os
        import subprocess as sp

        client_ip = str(self.cip.text()).replace(")","").replace("(","")
        client_port = str(self.cport.text()).replace(")","").replace("(","")
        server_ip = str(self.sip.text()).replace(")","").replace("(","")
        server_port = str(self.sport.text()).replace(")","").replace("(","")
        Network_Indicator = str(self.netindicator.text()).replace(")","").replace("(","")

        locael_GT = str(self.locael_gt.text()).replace(")","").replace("(","")

        Targer_MSISDN = str(self.msisdn.text()).replace(")","").replace("(","")


        

        atck_gui.attack_tracking_AnyTimeInterrogation(client_ip,client_port,server_ip,server_port,Network_Indicator,Targer_MSISDN,locael_GT)
        data = open('outingss7.txt','r').read().replace('[0m',' \n ').replace('\x1b[31m',' \n ').replace('\x1b[32m',' \n ').replace('\x1b',' \n ').replace('[34m',' ')
        self.output.append(str(data))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
