# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sigfremwork_gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1113, 787)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1111, 631))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./logo.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 640, 301, 151))
        self.label_2.setStyleSheet("font: italic 16pt \"Noto Sans\";")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1113, 23))
        self.menubar.setObjectName("menubar")
        self.menujkk = QtWidgets.QMenu(self.menubar)
        self.menujkk.setObjectName("menujkk")
        self.menuAttack_ss7 = QtWidgets.QMenu(self.menujkk)
        self.menuAttack_ss7.setObjectName("menuAttack_ss7")
        self.menuFraud_Info_Gathering = QtWidgets.QMenu(self.menuAttack_ss7)
        self.menuFraud_Info_Gathering.setObjectName("menuFraud_Info_Gathering")
        self.menuCall_and_SMS_Interception = QtWidgets.QMenu(self.menuAttack_ss7)
        self.menuCall_and_SMS_Interception.setObjectName("menuCall_and_SMS_Interception")
        self.menuLocation_Tracking = QtWidgets.QMenu(self.menuAttack_ss7)
        self.menuLocation_Tracking.setObjectName("menuLocation_Tracking")
        self.menuSimulator_ss7 = QtWidgets.QMenu(self.menujkk)
        self.menuSimulator_ss7.setObjectName("menuSimulator_ss7")
        self.menuFraud_Info_Gathering_2 = QtWidgets.QMenu(self.menuSimulator_ss7)
        self.menuFraud_Info_Gathering_2.setObjectName("menuFraud_Info_Gathering_2")
        self.menuCall_and_SMS_Interception_2 = QtWidgets.QMenu(self.menuSimulator_ss7)
        self.menuCall_and_SMS_Interception_2.setObjectName("menuCall_and_SMS_Interception_2")
        self.menuLocation_Tracking_2 = QtWidgets.QMenu(self.menuSimulator_ss7)
        self.menuLocation_Tracking_2.setObjectName("menuLocation_Tracking_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSendIMSI = QtWidgets.QAction(MainWindow)
        self.actionSendIMSI.setObjectName("actionSendIMSI")
        self.actionSendIMSI_2 = QtWidgets.QAction(MainWindow)
        self.actionSendIMSI_2.setObjectName("actionSendIMSI_2")
        self.actionMTForwardSMS = QtWidgets.QAction(MainWindow)
        self.actionMTForwardSMS.setObjectName("actionMTForwardSMS")
        self.actionMTForwardSMS_2 = QtWidgets.QAction(MainWindow)
        self.actionMTForwardSMS_2.setObjectName("actionMTForwardSMS_2")
        self.actionUpdateLocation = QtWidgets.QAction(MainWindow)
        self.actionUpdateLocation.setObjectName("actionUpdateLocation")
        self.actionUpdateLocation_2 = QtWidgets.QAction(MainWindow)
        self.actionUpdateLocation_2.setObjectName("actionUpdateLocation_2")
        self.actionSendRoutingInfo = QtWidgets.QAction(MainWindow)
        self.actionSendRoutingInfo.setObjectName("actionSendRoutingInfo")
        self.actionSendRoutingInfo_2 = QtWidgets.QAction(MainWindow)
        self.actionSendRoutingInfo_2.setObjectName("actionSendRoutingInfo_2")
        self.actionProvideSubsriberInfo = QtWidgets.QAction(MainWindow)
        self.actionProvideSubsriberInfo.setObjectName("actionProvideSubsriberInfo")
        self.actionProvideSubsriberInfo_2 = QtWidgets.QAction(MainWindow)
        self.actionProvideSubsriberInfo_2.setObjectName("actionProvideSubsriberInfo_2")
        self.actionSendRoutingInfoForSM = QtWidgets.QAction(MainWindow)
        self.actionSendRoutingInfoForSM.setObjectName("actionSendRoutingInfoForSM")
        self.actionSendRoutingInfoForSM_2 = QtWidgets.QAction(MainWindow)
        self.actionSendRoutingInfoForSM_2.setObjectName("actionSendRoutingInfoForSM_2")
        self.actionAnyTimeInterrogation = QtWidgets.QAction(MainWindow)
        self.actionAnyTimeInterrogation.setObjectName("actionAnyTimeInterrogation")
        self.actionAnyTimeInterrogation_2 = QtWidgets.QAction(MainWindow)
        self.actionAnyTimeInterrogation_2.setObjectName("actionAnyTimeInterrogation_2")
        self.actionSendRoutingInfoForGPRS = QtWidgets.QAction(MainWindow)
        self.actionSendRoutingInfoForGPRS.setObjectName("actionSendRoutingInfoForGPRS")
        self.actionSendRoutingInfoForGPRS_2 = QtWidgets.QAction(MainWindow)
        self.actionSendRoutingInfoForGPRS_2.setObjectName("actionSendRoutingInfoForGPRS_2")
        self.menuFraud_Info_Gathering.addAction(self.actionSendIMSI)
        self.menuFraud_Info_Gathering.addAction(self.actionMTForwardSMS)
        self.menuCall_and_SMS_Interception.addAction(self.actionUpdateLocation)
        self.menuLocation_Tracking.addAction(self.actionSendRoutingInfo)
        self.menuLocation_Tracking.addAction(self.actionProvideSubsriberInfo)
        self.menuLocation_Tracking.addAction(self.actionSendRoutingInfoForSM)
        self.menuLocation_Tracking.addAction(self.actionAnyTimeInterrogation)
        self.menuLocation_Tracking.addAction(self.actionSendRoutingInfoForGPRS)
        self.menuAttack_ss7.addAction(self.menuFraud_Info_Gathering.menuAction())
        self.menuAttack_ss7.addAction(self.menuLocation_Tracking.menuAction())
        self.menuAttack_ss7.addAction(self.menuCall_and_SMS_Interception.menuAction())
        self.menuFraud_Info_Gathering_2.addAction(self.actionSendIMSI_2)
        self.menuFraud_Info_Gathering_2.addSeparator()
        self.menuFraud_Info_Gathering_2.addAction(self.actionMTForwardSMS_2)
        self.menuCall_and_SMS_Interception_2.addAction(self.actionUpdateLocation_2)
        self.menuLocation_Tracking_2.addAction(self.actionSendRoutingInfo_2)
        self.menuLocation_Tracking_2.addAction(self.actionProvideSubsriberInfo_2)
        self.menuLocation_Tracking_2.addAction(self.actionSendRoutingInfoForSM_2)
        self.menuLocation_Tracking_2.addAction(self.actionAnyTimeInterrogation_2)
        self.menuLocation_Tracking_2.addAction(self.actionSendRoutingInfoForGPRS_2)
        self.menuSimulator_ss7.addAction(self.menuFraud_Info_Gathering_2.menuAction())
        self.menuSimulator_ss7.addAction(self.menuLocation_Tracking_2.menuAction())
        self.menuSimulator_ss7.addAction(self.menuCall_and_SMS_Interception_2.menuAction())
        self.menujkk.addAction(self.menuAttack_ss7.menuAction())
        self.menujkk.addAction(self.menuSimulator_ss7.menuAction())
        self.menubar.addAction(self.menujkk.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SigFramework"))
        self.label_2.setText(_translate("MainWindow", "SIG Framework\n"
"it\'s an update for sigploit "))
        self.menujkk.setTitle(_translate("MainWindow", "tools"))
        self.menuAttack_ss7.setTitle(_translate("MainWindow", "Attack_ss7"))
        self.menuFraud_Info_Gathering.setTitle(_translate("MainWindow", "Fraud & Info Gathering"))
        self.menuCall_and_SMS_Interception.setTitle(_translate("MainWindow", "Call and SMS Interception"))
        self.menuLocation_Tracking.setTitle(_translate("MainWindow", "Location Tracking"))
        self.menuSimulator_ss7.setTitle(_translate("MainWindow", "Simulator_ss7"))
        self.menuFraud_Info_Gathering_2.setTitle(_translate("MainWindow", "Fraud & Info Gathering"))
        self.menuCall_and_SMS_Interception_2.setTitle(_translate("MainWindow", "Call and SMS Interception"))
        self.menuLocation_Tracking_2.setTitle(_translate("MainWindow", "Location Tracking"))
        self.actionSendIMSI.setText(_translate("MainWindow", "SendIMSI"))
        self.actionSendIMSI_2.setText(_translate("MainWindow", "SendIMSI"))
        self.actionMTForwardSMS.setText(_translate("MainWindow", "MTForwardSMS"))
        self.actionMTForwardSMS_2.setText(_translate("MainWindow", "MTForwardSMS"))
        self.actionUpdateLocation.setText(_translate("MainWindow", "UpdateLocation"))
        self.actionUpdateLocation_2.setText(_translate("MainWindow", "UpdateLocation"))
        self.actionSendRoutingInfo.setText(_translate("MainWindow", "SendRoutingInfo"))
        self.actionSendRoutingInfo_2.setText(_translate("MainWindow", "SendRoutingInfo"))
        self.actionProvideSubsriberInfo.setText(_translate("MainWindow", "ProvideSubsriberInfo"))
        self.actionProvideSubsriberInfo_2.setText(_translate("MainWindow", "ProvideSubsriberInfo"))
        self.actionSendRoutingInfoForSM.setText(_translate("MainWindow", "SendRoutingInfoForSM"))
        self.actionSendRoutingInfoForSM_2.setText(_translate("MainWindow", "SendRoutingInfoForSM"))
        self.actionAnyTimeInterrogation.setText(_translate("MainWindow", "AnyTimeInterrogation"))
        self.actionAnyTimeInterrogation_2.setText(_translate("MainWindow", "AnyTimeInterrogation"))
        self.actionSendRoutingInfoForGPRS.setText(_translate("MainWindow", "SendRoutingInfoForGPRS"))
        self.actionSendRoutingInfoForGPRS_2.setText(_translate("MainWindow", "SendRoutingInfoForGPRS"))

        self.actionSendIMSI.triggered.connect(self.actionSendIMSI_win)
        self.actionSendIMSI_2.triggered.connect(self.actionSendIMSI_2_win)
        self.actionMTForwardSMS.triggered.connect(self.actionMTForwardSMS_win)
        self.actionMTForwardSMS_2.triggered.connect(self.actionMTForwardSMS_2_win)
        self.actionUpdateLocation.triggered.connect(self.actionUpdateLocation_win)
        self.actionUpdateLocation_2.triggered.connect(self.actionUpdateLocation_2_win)
        self.actionSendRoutingInfo.triggered.connect(self.actionSendRoutingInfo_win)
        self.actionSendRoutingInfo_2.triggered.connect(self.actionSendRoutingInfo2_win)
        self.actionProvideSubsriberInfo.triggered.connect(self.actionProvideSubsriberInfo_win)
        self.actionProvideSubsriberInfo_2.triggered.connect(self.actionProvideSubsriberInfo2_win)
        self.actionSendRoutingInfoForSM.triggered.connect(self.actionSendRoutingInfoForSM_win)
        self.actionSendRoutingInfoForSM_2.triggered.connect(self.actionSendRoutingInfoForSM2_win)
        self.actionAnyTimeInterrogation.triggered.connect(self.actionAnyTimeInterrogation_win)
        self.actionAnyTimeInterrogation_2.triggered.connect(self.actionAnyTimeInterrogation2_win)
        self.actionSendRoutingInfoForGPRS.triggered.connect(self.actionSendRoutingInfoForGPRS_win)
        self.actionSendRoutingInfoForGPRS_2.triggered.connect(self.actionSendRoutingInfoForGPRS2_win)

    def actionSendIMSI_win(self):
        from attack_SendIMSI import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionSendRoutingInfoForGPRS_win(self):
        from attack_tracking_SendRoutingInfoForGPRS import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionSendRoutingInfoForGPRS2_win(self):
        from simulator_tracking_SendRoutingInfoForGPRS import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionAnyTimeInterrogation_win(self):
        from attack_tracking_AnyTimeInterrogation import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionAnyTimeInterrogation2_win(self):
        from simulator_tracking_AnyTimeInterrogation import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionSendRoutingInfoForSM_win(self):
        from attack_tracking_SendRoutingInfoForSM import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionSendRoutingInfoForSM2_win(self):
        from simulator_tracking_SendRoutingInfoForSM import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionProvideSubsriberInfo_win(self):
        from attack_tracking_ProvideSubscriberInfo import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionProvideSubsriberInfo2_win(self):
        from simulator_tracking_ProvideSubscriberInfo import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionSendRoutingInfo_win(self):
        from attack_tracking_SendRoutingInfo import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionSendRoutingInfo2_win(self):
        from simulator_tracking_SendRoutingInfo import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionUpdateLocation_win(self):
        from attack_UpdateLocation import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()
    def actionUpdateLocation_2_win(self):
        from simulator_UpdateLocation import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionMTForwardSMS_win(self):
        from attack_MTForwardSMSResp import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionMTForwardSMS_2_win(self):
        from simulator_MTForwardSMSResp import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

    def actionSendIMSI_2_win(self):
        from simulator_SendIMSI import Ui_MainWindow
        self.Form = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Form)
        # MainWindow.close()
        self.Form.show()

def main_gui():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main_gui()
